name: lexpro
description: Dart lexer for various programming languages base on lex v0.0.1 originally published by thlorenz10@gmail.com edit by jackyanjiaqi@gmail.com
version: 2.1.0
homepage: https://github.com/zhuofaner/lexpro-dart

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  equatable: ^1.2.5

dev_dependencies:
  test: ^1.15.3

